# Generated by Django 2.0.9 on 2018-12-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pH', models.IntegerField(default=0)),
                ('temp', models.IntegerField(default=0)),
                ('Ec', models.IntegerField(default=0)),
                ('Water', models.IntegerField(default=0)),
            ],
        ),
    ]
