# Generated by Django 2.0.9 on 2018-12-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dt',
            name='Ec',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='dt',
            name='Water',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='dt',
            name='pH',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='dt',
            name='temp',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
