# Generated by Django 2.0.9 on 2018-12-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181213_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dt',
            name='Ec',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dt',
            name='Water',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dt',
            name='pH',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dt',
            name='temp',
            field=models.IntegerField(default=0),
        ),
    ]
