# Generated by Django 2.0.9 on 2018-12-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181213_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='dt2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pH', models.IntegerField(default=0)),
                ('temp', models.IntegerField(default=0)),
                ('Ec', models.IntegerField(default=0)),
                ('Water', models.IntegerField(default=0)),
            ],
        ),
    ]
