# Generated by Django 2.0.9 on 2018-12-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_dt2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dt',
            name='Ec',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='dt',
            name='Water',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='dt',
            name='pH',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='dt',
            name='temp',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='dt2',
            name='Ec',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='dt2',
            name='Water',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='dt2',
            name='pH',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='dt2',
            name='temp',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
