# Generated by Django 2.0.9 on 2018-12-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20181214_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='vegetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vegetable', models.CharField(choices=[('FR', 'Asparagus'), ('SO', 'Broccoli'), ('JR', 'Red_Oak_Lettuce')], default='FR', max_length=2)),
            ],
        ),
    ]
