# Generated by Django 2.0.9 on 2018-12-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_vegetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vegetable',
            name='Vegetable',
        ),
        migrations.AddField(
            model_name='vegetable',
            name='Asparagus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vegetable',
            name='Broccoli',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vegetable',
            name='Red_Oak_Lettuce',
            field=models.BooleanField(default=False),
        ),
    ]
