# Generated by Django 2.0.9 on 2018-12-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20181214_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetable',
            name='Asparagus',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vegetable',
            name='Broccoli',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vegetable',
            name='Red_Oak_Lettuce',
            field=models.BooleanField(default=True),
        ),
    ]
