# Generated by Django 2.0.9 on 2018-12-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mode',
            old_name='Mode',
            new_name='Auto',
        ),
        migrations.AddField(
            model_name='mode',
            name='Manual',
            field=models.BooleanField(default=True),
        ),
    ]
