# Generated by Django 2.0.9 on 2018-12-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20181215_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mode',
            name='Auto',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mode',
            name='Manual',
            field=models.BooleanField(default=True),
        ),
    ]
