# Generated by Django 2.0.9 on 2018-12-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20181215_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mode',
            name='Auto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mode',
            name='Manual',
            field=models.BooleanField(default=False),
        ),
    ]
